Building with responsive design. Project #6 Microverse.
SigmaSam/Building-with-Responsive-Design-Samuel-Juan pull request #5
Opened 2020-05-21 14:13 UTC by SigmaSam

2020-05-21 20:42 UTC, SigmaSam commented
### Replicated the TNW website.
- Build an HTML and CSS responsive design.
- Worked with Grid and Flex to create a responsive design.
- Gave the website a breakpoint at 76Xpx screen width to be adapted to smaller devices.

2020-05-21 21:09 UTC, SigmaSam commented
### Replicated the TNW website.
- Build an HTML and CSS responsive design.
- Worked with Grid and Flex to create a responsive design.
- Gave the website a breakpoint at 76Xpx screen width to be adapted to smaller devices.

2020-05-22 01:46 UTC, christianotieno requested changes
# **CHANGES REQUIRED** :warning:
Hey @SigmaSam & @jacobo12montes  :wave:
-
You have done a splendid job! :tada: Keep it up.
We, however, do have some few changes to carry out before we proceed (see review comment).
##
## Required
- [x] In the top left main article, the date and the main red gradient are missing. Please add them. See the difference below 👇 

|[Source](https://thenextweb.com/)|[Clone](https://rawcdn.githack.com/SigmaSam/Building-with-Responsive-Design-Samuel-Juan/f49fa110b5115a7ca02139dd883880e176a1ab00/index.html)|
|:---:|:---:|
|![large_screen](https://user-images.githubusercontent.com/22345961/82621443-cc8e9800-9be3-11ea-89de-3a254818344a.png)|![large_screen-clone](https://user-images.githubusercontent.com/22345961/82621465-d9ab8700-9be3-11ea-9cd5-f76e39a1ead6.png)|

### Medium Screen Changes
- [x] The contents should be fitting the entire width of the view. Currently, we have some unnecessary space (margin) in the following sections. See the changes below 👇 

- The latest news section:

|[Source](https://thenextweb.com/)|[Clone](https://rawcdn.githack.com/SigmaSam/Building-with-Responsive-Design-Samuel-Juan/f49fa110b5115a7ca02139dd883880e176a1ab00/index.html)|
|:---:|:---:|
|![medium-screen](https://user-images.githubusercontent.com/22345961/82622006-5a1eb780-9be5-11ea-8c9c-95f0776c54e6.png)|![medium-screenclone](https://user-images.githubusercontent.com/22345961/82622010-60ad2f00-9be5-11ea-8d07-d8e6fdaaf288.png)|

- The two article section: 

|[Source](https://thenextweb.com/)|[Clone](https://rawcdn.githack.com/SigmaSam/Building-with-Responsive-Design-Samuel-Juan/f49fa110b5115a7ca02139dd883880e176a1ab00/index.html)|
|:---:|:---:|
|![two-articles-medium](https://user-images.githubusercontent.com/22345961/82621770-bc2aed00-9be4-11ea-9e25-333873ed5714.png)|![two-articles-medium-clone](https://user-images.githubusercontent.com/22345961/82621804-cc42cc80-9be4-11ea-9830-fd7822b1113e.png)|

- There is a slight difference in the latest deals section

|[Source](https://thenextweb.com/)|[Clone](https://rawcdn.githack.com/SigmaSam/Building-with-Responsive-Design-Samuel-Juan/f49fa110b5115a7ca02139dd883880e176a1ab00/index.html)|
|:---:|:---:|
|![latest-deals-medium](https://user-images.githubusercontent.com/22345961/82622194-d1ece200-9be5-11ea-989f-8733378ee14e.png)|![latest-deals-clone](https://user-images.githubusercontent.com/22345961/82622205-d9ac8680-9be5-11ea-83de-78514c72fb66.png)|
##
### Small Screen Changes
- [x] In the small screen changes, all images take the maximum width and should be aligned in one column ([link to page](https://thenextweb.com/)).
- [x] Navigation and sub-navigation row changes to a hamburger (bars) icon at the rightmost part (next to search icon) ([link to page](https://thenextweb.com/))

|[Source](https://thenextweb.com/)|[Clone](https://rawcdn.githack.com/SigmaSam/Building-with-Responsive-Design-Samuel-Juan/f49fa110b5115a7ca02139dd883880e176a1ab00/index.html)|
|:---:|:---:|
|![small-screen](https://user-images.githubusercontent.com/22345961/82622305-1b3d3180-9be6-11ea-909d-1df464e3b3b0.png)|![small-screen-clome](https://user-images.githubusercontent.com/22345961/82622317-22643f80-9be6-11ea-9f69-e85a091bacc2.png)|

- [x] Make sure that basic CSS bad practices are not used ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright).

- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

2020-05-23 15:51 UTC, lucasmazo32 requested changes
# Changes required :wrench:

You are doing a great job so far, and the project is looking good. 

For the project to get approved, kindly implement the changes mentioned below.

### Happy coding! :computer:

## Lucas Mazo

2020-05-23 15:51 UTC, lucasmazo32 commented on index.html
> +        </div>
- [ ] The logo in the first article should not appear when the logo appears in the navbar.
> Source
![](https://user-images.githubusercontent.com/57414789/82734453-ae5a9200-9ce0-11ea-9c33-21cbb6728013.png) 

>Clone
![](https://user-images.githubusercontent.com/57414789/82734474-d6e28c00-9ce0-11ea-9de8-7ccf3fac239d.png)

2020-05-23 15:51 UTC, lucasmazo32 commented on index.html
> +        <h2 class="lastest__title"><a href="#">Lastest news ></a></h2>
- [ ] Kindly fix the layout of the Latest news section for medium screens.

> Source 
![image](https://user-images.githubusercontent.com/57414789/82734769-aef42800-9ce2-11ea-8f8b-783417894cd3.png)


> Clone
![image](https://user-images.githubusercontent.com/57414789/82734754-9f74df00-9ce2-11ea-8322-1f99a32375e3.png)

2020-05-23 15:51 UTC, lucasmazo32 commented on index.html
> +          <div class="categories">
- [ ] Kindly fix the layout for medium screens:

> Source 
![image](https://user-images.githubusercontent.com/57414789/82734822-08f4ed80-9ce3-11ea-9086-72e386a8e3de.png)

> Clone
![image](https://user-images.githubusercontent.com/57414789/82734817-fd092b80-9ce2-11ea-8f6d-bb70e00a2031.png)

2020-05-23 15:51 UTC, lucasmazo32 commented on index.html
> +            <p class="latest_deals11">Latest Deals ></p>
- [ ] Kindly fix the layout for latest deals for medium screens.

> Source
![image](https://user-images.githubusercontent.com/57414789/82734860-35a90500-9ce3-11ea-956d-10a98a74242f.png)

> Clone
![image](https://user-images.githubusercontent.com/57414789/82734867-42c5f400-9ce3-11ea-82f0-fbefce759341.png)

2020-05-25 10:55 UTC, SigmaSam commented
New Features.
- Improved responsiveness for small and big screens.
- Add medium screen breakpoint and design.
- Fixed issues mentined in previus reviews.

2020-05-25 18:59 UTC, addod19 commented
## Pull Request under review by Daniel Larbi Addo (TSE)

2020-05-25 19:03 UTC, addod19 approved these changes
## Status: Approved :trophy: :balloon: 

Hi **TEAM**, congratulations on fixing all the changes required by the previous TSE's :+1:  Your project now meets the minimum requirements to get approved :slightly_smiling_face: I, therefore, approve your project. You can go ahead and merge to master.
Do not forget to submit the project completion form

_Happy coding_ :man_technologist: 
Good luck with your next projects
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2020-05-25 23:00 UTC, merged